services:
  db:
    image: mysql:9.0
    container_name: mysql_cappelli
    restart: always
    environment:
      MYSQL_DATABASE: catalogo_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: app_cappelli
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/catalogo_db?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - app-network
    depends_on:
      - db
    volumes:
      - ./uploads:/app/uploads 

networks:
  app-network:
    driver: bridge

volumes:
  db_data: